In [1]:
from vllm import LLM, SamplingParams
from vllm.lora.request import LoRARequest

/home/ray/anaconda3/envs/myenv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2024-04-24 21:21:49,754	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.


In [2]:
import pickle

with open('control_vectors_high.pkl', 'rb') as file:
    loaded_controlVector = pickle.load(file)

In [3]:
from vllm.config import ControlVectorConfig
from vllm.control_vectors.control import ControlVector

In [4]:
cv = ControlVector(model_type='mixtral', directions=loaded_controlVector.directions)

In [5]:
control_vector_config = ControlVectorConfig(layer_ids=list(cv.directions.keys()), control_vector=cv)

In [6]:
llm = LLM(model='mistralai/Mistral-7B-Instruct-v0.1', control_vector_config=control_vector_config, enforce_eager=True, dtype="float16", max_model_len=15376)
# llm = LLM(model='mistralai/Mistral-7B-Instruct-v0.1', enforce_eager=True, dtype="float16", max_model_len=15376)

WARNING 04-24 21:21:51 config.py:953] Casting torch.bfloat16 to torch.float16.
INFO 04-24 21:21:51 llm_engine.py:82] Initializing an LLM engine (v0.4.0.post1) with config: model='mistralai/Mistral-7B-Instruct-v0.1', speculative_config=None, tokenizer='mistralai/Mistral-7B-Instruct-v0.1', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=15376, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, seed=0)
INFO 04-24 21:21:51 pynccl.py:58] Loading nccl from library /home/ray/.config/vllm/nccl/cu12/libnccl.so.2.18.1
INFO 04-24 21:21:52 selector.py:77] Cannot use FlashAttention backend because the flash_attn package is not found. Please install it for better performance.
INFO 04-24 21:21:52 selector.py:33] Using XFormers backend.
CONTROL VECTORS ControlVectorConfig(layer_ids=

In [7]:
prompts = [
    "How are you feeeling right noww?"
]
sampling_params = SamplingParams(max_tokens=100)

In [8]:
outputs = llm.generate(prompts, sampling_params)


Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s]

tensor([-0.0112,  0.0050, -0.0089,  ...,  0.0021,  0.0069,  0.0070],
       dtype=torch.float16)
very start control vector tensor([-0.0112,  0.0050, -0.0089,  ...,  0.0021,  0.0069,  0.0070],
       dtype=torch.float16)
after to tensor([-0.0112,  0.0050, -0.0089,  ...,  0.0021,  0.0069,  0.0070],
       device='cuda:0', dtype=torch.float16)
Control vector sample: tensor([-0.0112,  0.0050, -0.0089,  0.0002, -0.0097, -0.0155, -0.0081,  0.0040,
         0.0004,  0.0036], device='cuda:0', dtype=torch.float16)
Mask sample: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0')
Control vector sample after: tensor([-0.0112,  0.0050, -0.0089,  0.0002, -0.0097, -0.0155, -0.0081,  0.0040,
         0.0004,  0.0036], device='cuda:0')
tensor([-0.0058,  0.0060,  0.0034,  ...,  0.0035,  0.0111,  0.0069],
       dtype=torch.float16)
very start control vector tensor([-0.0058,  0.0060,  0.0034,  ...,  0.0035,  0.0111,  0.0069],
       dtype=torch.float16)
after to tensor([-0.0058,  0.0060,  0

Processed prompts: 100%|██████████| 1/1 [00:17<00:00, 17.42s/it]

tensor([-0.0139,  0.0026, -0.0062,  0.0065, -0.0108,  0.0060,  0.0112,  0.0019,
        -0.0077,  0.0024], device='cuda:0')
tensor([-0.0122,  0.0047, -0.0075,  ..., -0.0034, -0.0017, -0.0037],
       dtype=torch.float16)
very start control vector tensor([-0.0122,  0.0047, -0.0075,  ..., -0.0034, -0.0017, -0.0037],
       dtype=torch.float16)
after to tensor([-0.0122,  0.0047, -0.0075,  ..., -0.0034, -0.0017, -0.0037],
       device='cuda:0', dtype=torch.float16)
Control vector sample: tensor([-0.0122,  0.0047, -0.0075,  0.0073, -0.0099,  0.0057,  0.0144,  0.0010,
        -0.0125,  0.0039], device='cuda:0', dtype=torch.float16)
Mask sample: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0')
Control vector sample after: tensor([-0.0122,  0.0047, -0.0075,  0.0073, -0.0099,  0.0057,  0.0144,  0.0010,
        -0.0125,  0.0039], device='cuda:0')
tensor([-0.0022,  0.0090,  0.0110,  ...,  0.0106,  0.0105,  0.0010],
       dtype=torch.float16)
very start control vector tensor([-0

In [9]:
printoutputs

[RequestOutput(request_id=0, prompt='How are you feeeling right noww?', prompt_token_ids=[1, 1602, 460, 368, 10351, 9365, 1103, 1055, 28727, 28804], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='\nUser 8: Wooooooooooooooooooooooooooooooooooooooooo the colors you seeeeeeeeeeeeeeeeeeeeeeeeee title of the artwork\n\nThe landscape of colours melting before you swirl around and around swirling and swirling and swirling\n\nSoft brush strokes painting the world of your imagination\n\nInfinite possibilities of colours constantly flowing and pulsating\n\nDancing around the dream world cosmos of wondrous colours\n', token_ids=[13, 730, 28705, 28783, 28747, 394, 24438, 24438, 24438, 24438, 24438, 24438, 24438, 24438, 24438, 24438, 28709, 272, 9304, 368, 1032, 2443, 2443, 2443, 2443, 2443, 2443, 2443, 2443, 2443, 2443, 2443, 2443, 3941, 302, 272, 27261, 13, 13, 1014, 13894, 302, 22137, 8970, 1157, 1159, 368, 1719, 2156, 1401, 304, 1401, 1719, 26692, 304, 1719, 26692, 304, 1719, 26

In [10]:
[RequestOutput(request_id=1, prompt='Are you superhappy', prompt_token_ids=[1, 4867, 368, 2195, 28716, 9813], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text=' yet? There\'s nothing quite as exhilarating as sending an email to someone title-free and watching your recipient look at it, wondering who did that. If you think there\'s no more effective way to grab someone\'s attention than a subject line, you\'re dead wrong. Here are nine tips for crafting emails that get opened (without subject lines) and some of the best subject line alternatives I\'ve ever come across. \n\n1. Start With a Question:\n\nInstead of a subject line, you can start your email with a question. For instance, "Has anything changed since we last talked?" You can also use an exclamation mark to add urgency to the question. For example, "Hey [Recipient], Do you need this now?" \n\n2. Use Emoticons:\n\nEmoticons are the new subject lines. By using emojis in your email, you can convey your mood and', token_ids=[2783, 28804, 1387, 28742, 28713, 2511, 3448, 390, 26112, 3052, 1077, 390, 10313, 396, 4927, 298, 2493, 3941, 28733, 3669, 304, 6265, 574, 23841, 913, 438, 378, 28725, 12785, 693, 863, 369, 28723, 1047, 368, 1073, 736, 28742, 28713, 708, 680, 5645, 1069, 298, 7290, 2493, 28742, 28713, 4501, 821, 264, 3817, 1407, 28725, 368, 28742, 267, 3694, 3544, 28723, 4003, 460, 9542, 10636, 354, 9949, 288, 19863, 369, 625, 4923, 325, 20795, 3817, 4715, 28731, 304, 741, 302, 272, 1489, 3817, 1407, 24524, 315, 28742, 333, 2270, 1567, 2673, 28723, 28705, 13, 13, 28740, 28723, 7043, 2326, 264, 22478, 28747, 13, 13, 6060, 1109, 302, 264, 3817, 1407, 28725, 368, 541, 1149, 574, 4927, 395, 264, 2996, 28723, 1263, 3335, 28725, 345, 5402, 2424, 4648, 1854, 478, 1432, 9409, 1110, 995, 541, 835, 938, 396, 5420, 314, 352, 1716, 298, 967, 13839, 2090, 298, 272, 2996, 28723, 1263, 2757, 28725, 345, 15766, 733, 3755, 508, 722, 1181, 2378, 368, 927, 456, 1055, 1110, 28705, 13, 13, 28750, 28723, 5938, 2929, 7839, 1053, 28747, 13, 13, 3729, 7839, 1053, 460, 272, 633, 3817, 4715, 28723, 2463, 1413, 877, 6054, 278, 297, 574, 4927, 28725, 368, 541, 18887, 574, 12247, 304], cumulative_logprob=-288.01711124065696, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1714016968.341816, last_token_time=1714016968.341816, first_scheduled_time=1714016968.3447053, first_token_time=1714016968.4299927, time_in_queue=0.002889394760131836, finished_time=1714016981.8023434), lora_request=None)]

NameError: name 'RequestOutput' is not defined